### ISSUE TITLE
General todo list

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/mbs#13]
Just a collection of features it didn't seem worth creating separate issues for.

## Readline
 - [ ] Add history search: This should appear relatively similar to autocompletion, with the currently entered text in white and the remaining text in grey. We'd want to have some indicator marking that we're in search mode.

   <kbd>C-R</kbd> should search backwards and <kbd>C-S</kbd> to search forwards. <kbd>C-G</kbd> will clear the search, any non-character key will accept it. Basically how normal readline works.

## Lua
 - [ ] Show a similar traceback on errors to that in `shell`.
 - [ ] Improve the pretty printer, so it is smarter on when it wraps entries. Also have a depth and table/string length limit, so we don't spam the console with junk.

   There's a bit of me which would like to use some Wadler-esque pretty printer, but it'd probably overkill. Maybe as a separate module. It might also be nice to have some syntax highlighting (colour numbers and strings, symbols, etc...) in the output.

## Shell
 - [ ] Only trim the traceback parts of the error message, not the error message itself. We should probably look into finding the last instance of `stack traceback` or something. Alternatively, just fix it in Cobalt and ignore people on vanilla CC :p.
